name: Build PowerShell EXE using ps2exe

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch payload'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install ps2exe module
    - name: Install ps2exe Module
      shell: powershell
      run: |
        Install-Module -Name ps2exe -Force -Scope CurrentUser

    # Step 3: Fetch the payload script from the provided URL and save it
    - name: Fetch Payload Script
      shell: powershell
      run: |
        $url = '${{ github.event.inputs.payload_url }}'
        Invoke-WebRequest -Uri $url -OutFile 'payload.ps1'

    # Step 4: Convert PowerShell script to an executable
    - name: Convert PowerShell Script to EXE
      shell: powershell
      run: |
        ps2exe -inputFile '.\payload.ps1' -outputFile '.\payload.exe' -noConsole

    # Step 5: List the contents of the output directory
    - name: List Directory Contents
      shell: powershell
      run: Get-ChildItem -Path .

    # Step 6: Upload the generated EXE as an artifact
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: payload_exe
        path: payload.exe






