name: Build PowerShell EXE using ps2exe

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch payload'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Download ps2exe module
    - name: Download ps2exe module
      run: |
        Install-Module -Name ps2exe -Force -Scope CurrentUser

    # Step 3: Fetch the payload script from the provided URL and save it
    - name: Fetch Payload from URL
      run: |
        $url = '${{ github.event.inputs.payload_url }}'
        $payload = Invoke-WebRequest -Uri $url -OutFile 'payload.ps1'
        Write-Host "[INFO] Payload script downloaded."

    # Step 4: Convert the PowerShell script to an executable
    - name: Convert PowerShell script to EXE using ps2exe
      run: |
        ps2exe .\payload.ps1 .\payload.exe
        Write-Host "[INFO] Payload converted to EXE."

    # Step 5: List the contents of the output directory
    - name: List contents of the output directory
      run: |
        dir

    # Step 6: Upload the executable as an artifact
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: payload_exe
        path: payload.exe
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false




