name: Build PowerShell EXE (IExpress)

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch PowerShell script'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Check IExpress Availability
      shell: cmd
      run: |
        where iexpress || echo "IExpress is missing!" > iexpress_missing.txt

    - name: Fetch Payload Script
      shell: powershell
      run: |
        Invoke-WebRequest -Uri '${{ github.event.inputs.payload_url }}' -OutFile 'payload.ps1'

    - name: Verify Payload File
      shell: cmd
      run: |
        if not exist "payload.ps1" echo "Payload script is missing!" && exit 1

    - name: Create IExpress SED File
      shell: cmd
      run: |
        echo [Version] > package.sed
        echo Class=IEXPRESS >> package.sed
        echo SEDVersion=3 >> package.sed
        echo [Options] >> package.sed
        echo PackagePurpose=InstallApp >> package.sed
        echo ShowInstallProgramWindow=0 >> package.sed
        echo HideExtractAnimation=1 >> package.sed
        echo UseLongFileNames=1 >> package.sed
        echo TargetName="%TEMP%\payload.exe" >> package.sed
        echo [Files] >> package.sed
        echo payload.ps1 >> package.sed
        echo [Strings] >> package.sed
        echo InstallProgram=powershell.exe -ExecutionPolicy Bypass -File payload.ps1 >> package.sed

    - name: Run IExpress
      shell: cmd
      run: |
        iexpress /N /Q package.sed > iexpress_log.txt 2>&1 || (
          echo "IExpress failed!" 
          type iexpress_log.txt
          exit 1
        )

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: payload_exe
        path: "%TEMP%/payload.exe"
