name: Build PowerShell EXE using IExpress

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch payload script'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Fetch PowerShell Script from URL
    - name: Fetch Payload Script
      shell: powershell
      run: |
        $url = '${{ github.event.inputs.payload_url }}'
        Invoke-WebRequest -Uri $url -OutFile 'payload.ps1'
        if (!(Test-Path "payload.ps1")) { throw "Payload download failed!" }

    # Step 3: Generate IExpress SED Configuration File
    - name: Create IExpress SED File
      shell: powershell
      run: |
        @'
        [Version]
        Class=IEXPRESS
        SEDVersion=3
        [Options]
        PackagePurpose=InstallApp
        ShowInstallProgramWindow=1
        HideExtractAnimation=0
        UseLongFileName=1
        InsideCompressed=0
        CAB_FixedSize=0
        RebootMode=N
        InstallPrompt=
        DisplayLicense=
        FinishMessage=
        TargetName=payload.exe
        FriendlyName=PowerShell Payload
        AppLaunched=powershell.exe -ExecutionPolicy Bypass -File payload.ps1
        PostInstallCmd=<None>
        AdminQuietInstCmd=
        UserQuietInstCmd=
        SourceFiles=SourceFiles
        [SourceFiles]
        SourceFiles0=payload.ps1
        [Strings]
        AppName=PowerShell Payload
        ' | Set-Content -Path "package.sed" -Encoding ASCII

    # Step 4: Run IExpress to Create EXE
    - name: Run IExpress
      shell: cmd
      run: |
        iexpress /N /Q package.sed > iexpress_log.txt 2>&1 || exit 1

    # Step 5: Upload Log File for Debugging
    - name: Upload IExpress Log
      uses: actions/upload-artifact@v4
      with:
        name: iexpress_log
        path: iexpress_log.txt

    # Step 6: Upload the Generated EXE
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: payload_exe
        path: payload.exe

