name: Build EXE using IExpress

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Verify IExpress is available
    - name: Check if IExpress is installed
      shell: cmd
      run: |
        where iexpress || (echo "IExpress is missing!" && exit /b 1)

    # Step 3: Validate the package.sed file before running IExpress
    - name: Validate package.sed file
      shell: cmd
      run: |
        echo "Checking package.sed file contents:"
        type package.sed

    # Step 4: Run IExpress in Debug Mode (Manual Mode)
    - name: Debug IExpress in Interactive Mode
      shell: cmd
      run: |
        iexpress /M package.sed

    # Step 5: Run IExpress to create EXE
    - name: Run IExpress to build EXE
      shell: cmd
      run: |
        iexpress /N /Q package.sed > iexpress_log.txt 2>&1
        if %ERRORLEVEL% NEQ 0 (
          echo "IExpress failed! Log output:"
          type iexpress_log.txt
          exit /b %ERRORLEVEL%
        )

    # Step 6: List directory to check if EXE was created
    - name: List output directory
      shell: cmd
      run: dir

    # Step 7: Upload the generated EXE as an artifact
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: built_exe
        path: "*.exe"

    # Step 8: Upload the IExpress log for debugging (if it failed)
    - name: Upload IExpress Log (if failed)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: iexpress_log
        path: iexpress_log.txt

