name: Build PowerShell EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .NET console project
      run: |
        dotnet new console -o PowerShellRunner
        cp -Force Program.cs PowerShellRunner/
        cd PowerShellRunner
        dotnet add package Microsoft.PowerShell.SDK

    - name: Build EXE
      run: |
        cd PowerShellRunner
        dotnet build -c Release

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: payload_exe
        path: PowerShellRunner/bin/Release/**/PowerShellRunner.exe




